spring:
    profiles:
        active:
        - dev
---
spring:
    profiles : dev # 开发环境
    appllcatlo :
        name : microservicecloud-config-atguigu-dev
---
spring:
    profiles : test # 测试环境
    application :
        name : microservicecloud-config-atguigu-test
# 保存问utf-8